---
galaxy_info:
  author: CloudKit E2E Testing
  description: Base role for fulfillment-cli operations in CloudKit E2E tests
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"
  galaxy_tags:
    - cloudkit
    - testing
    - e2e
    - openshift
    - fulfillment

dependencies: []

collections:
  - kubernetes.core
  - ansible.posix
